network:
  # Network type (mainnet/testnet)
  network: "testnet"

  # Ogmios/Kupo configuration for local testnet
  ogmios_kupo:
    ogmios_url: "http://localhost:1337"
    kupo_url: "http://localhost:1442"

# Wallet configuration - use either mnemonic or key files
wallet:
  mnemonic: "$TESTNET_WALLET_MNEMONIC"

oracle_address: "addr1..."
policy_id: "..."

tokens:
  reward_token_policy: "hex_policy_id_here"
  reward_token_name: "hex_token_name_here"

  rate_token_policy: "hex_policy_id_here"
  rate_token_name: "hex_token_name_here"

reference_script:
  # Will pay out utxo with reference script to this address. And lookup the script utxo at this address.
  address: "addr..."
  # Looking through all utxos at an address could be inefficient. Provide optional utxo reference to speed up the reference script query.
  utxo_reference:
    transaction_id: "4606793120f127744d2b2f3bcc265a9a91eea8693f6eee2f48287738edededed"
    output_index: 1

# Simulation-specific settings
simulation:
  node_keys_dir: "node_keys"
  base_feed: 100
  variance: 0.02
  wait_time: 60
