aggstate_count: 3
apply_arguments_with_aiken: true
blueprint_path: ../artifacts/testnet_plutus.json
create_reference: true
fees:
  node_fee: 100
  platform_fee: 100
multisig:
  parties:
  - c8c47610a36034aac6fc58848bdae5c278d994ff502c05455e3b3ee8
  platform_addr: addr_test1wp653q94ze4kc7xfffgpwrfpan79m0z7x3hvfqeczhp6uug6fwg8n
  threshold: 1
network:
  network: testnet
  ogmios_kupo:
    kupo_url: http://localhost:1442
    ogmios_url: ws://localhost:1337
  wallet:
    mnemonic: test test test test test test test test test test test test test test
      test test test test test test test test test sauce
nodes:
  feed_vkh:
  - f35b6075f98a70b836d4c7b9dd6f174dfa162a61f73e7074e7b4d70b
  - 0cc83e026a953bd53b5e8867a5022705844e24ddf28f23280df39d22
  - 09d7ce6ab1f6e2197a0dc83fe374b71b0ef2b1293c9225564c831425
  - cd623bb59c87896a5a295d188a99822fdf0ca611e135d75a114464da
  - 228f1aa03e1d3e68a066e05c5df568fd5815efb6f3405e0968e187d6
  - 5a84f29eb6579f3753845dd62e0b0f294266039e64a3bf6d5113b166
  - f7597713d95788d0ede6c90509a7d10d1eb3914fe879f2172bf907c7
  - d7a6019ef1992df288c36617a0d554cbdd747c4c948fd20a22bdcd5e
  - 4966131de699f3bd2d55aff6df158fcd885d06d0d6b8e8c323914bbf
  required_signatures: 9
oracle_address: addr_test1wphe4kdku5kuq29u7mj002r524du8gv9u2fvmmyygqc7t8swft3ke
reference_script_addr: addr_test1wqnk0zrhwleqvkhcn3d3uygrsu6xupqefnxdxv6lv79l9hgag9z52
reward_count: 3
timing:
  aggregation_liveness: 65000
  iqr_multiplier: 150
  median_divergency_factor: 200
  pause_period: 65000
  reward_dismissing_period: 65000
  time_uncertainty_aggregation: 5000
  time_uncertainty_platform: 60000
tokens:
  fee_token_name: '546573744333'
  fee_token_policy: 4d5054a6d395e1ce2defdbb1c89ae6808561c45590cb4a05be46ec0a
  oracle_policy: cb1dc6888502ce5717ca3a5bd3bd4274a0f6f76830740cece9062521
  platform_auth_policy: ba5eb2a06afed80d7d6d91df0997f6dd34250c3dcf57fd0ca18fbe10
