blueprint_path: ../artifacts/testnet_plutus.json
create_reference: true
fees:
  node_fee: 100
  platform_fee: 100
multisig:
  parties:
  - c8c47610a36034aac6fc58848bdae5c278d994ff502c05455e3b3ee8
  platform_addr: addr_test1wp653q94ze4kc7xfffgpwrfpan79m0z7x3hvfqeczhp6uug6fwg8n
  threshold: 1
network:
  network: testnet
  ogmios_kupo:
    kupo_url: http://localhost:1442
    ogmios_url: ws://localhost:1337
  wallet:
    mnemonic: test test test test test test test test test test test test test test
      test test test test test test test test test sauce
nodes:
  nodes:
  - feed_vkh: f35b6075f98a70b836d4c7b9dd6f174dfa162a61f73e7074e7b4d70b
    payment_vkh: c8c47610a36034aac6fc58848bdae5c278d994ff502c05455e3b3ee8
  - feed_vkh: 0cc83e026a953bd53b5e8867a5022705844e24ddf28f23280df39d22
    payment_vkh: a283d083ef2b398362c4a24d3cb0d52d0b197d2158cfbe2a4cf4899f
  - feed_vkh: 09d7ce6ab1f6e2197a0dc83fe374b71b0ef2b1293c9225564c831425
    payment_vkh: dcf1967142a82089238978008350a4b159aeae5058acf4d38c8cc642
  - feed_vkh: cd623bb59c87896a5a295d188a99822fdf0ca611e135d75a114464da
    payment_vkh: eece186c6f3d39f29dee71a516d72f1d7c8559595d6770341c3a6ca9
  - feed_vkh: 228f1aa03e1d3e68a066e05c5df568fd5815efb6f3405e0968e187d6
    payment_vkh: 17c578b000ec6b1fdd94df03e1148d648da057f3d2fa7dc492efcd1a
  - feed_vkh: 5a84f29eb6579f3753845dd62e0b0f294266039e64a3bf6d5113b166
    payment_vkh: 7d0bfa594243fc2cd31c4bf92f1356f5878555cf5a379d4bf3df5595
  - feed_vkh: f7597713d95788d0ede6c90509a7d10d1eb3914fe879f2172bf907c7
    payment_vkh: e4057c06b5171bcc9690960d3dfdb1bfd689b15b0f931e171143782b
  - feed_vkh: d7a6019ef1992df288c36617a0d554cbdd747c4c948fd20a22bdcd5e
    payment_vkh: 7090ccc2db3d0b090d436fee49cd22b2b07a9837b32754bf590faf07
  - feed_vkh: 4966131de699f3bd2d55aff6df158fcd885d06d0d6b8e8c323914bbf
    payment_vkh: 4a30d28918afaf4cc797f3e6a5e78d83c18b753ec44fc4d3a2ed9863
  required_signatures: 9
oracle_address: addr_test1wqa4s0e83mfceqtwxpecf3vcqmzst9l4xuqn0ya4zsuf8rqfz7uu0
reference_script_addr: addr_test1wqnk0zrhwleqvkhcn3d3uygrsu6xupqefnxdxv6lv79l9hgag9z52
reward_issuer_address: addr_test1qryvgass5dsrf2kxl3vgfz76uhp83kv5lagzcp29tcana68ca5aqa6swlq6llfamln09tal7n5kvt4275ckwedpt4v7q48uhex
timing:
  aggregation_liveness: 300000
  iqr_multiplier: 150
  median_divergency_factor: 200
  pause_period: 300000
  reward_dismissing_period: 600000
  time_uncertainty_aggregation: 60000
  time_uncertainty_platform: 90000
tokens:
  fee_token_name: '546573744333'
  fee_token_policy: 336f96b87637276aae4742af016fadfd489a16895d82b792a08900ec
  oracle_policy: 6c120d1e48e04991b833f3fb910c172741178c91a5eb90441c6fa5ad
  platform_auth_policy: 813d7b9a90f8354c30eaacf49e02f2d3a6c059299073ff73bf93e404
transport_count: 4
